"""add_amount_usd_equivalent_field

Revision ID: 080e138beb3e
Revises: 826026dec36c
Create Date: 2025-12-13 19:46:47.473555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '080e138beb3e'
down_revision: Union[str, Sequence[str], None] = '826026dec36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_payment_events', sa.Column('amount_usd_equivalent', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('normalized_payment_events', 'amount_usd_equivalent')
    # ### end Alembic commands ###
