"""create_normalized_payment_events_table

Revision ID: 10309e03c6ad
Revises:
Create Date: 2025-12-13 17:28:07.778922

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '10309e03c6ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_payment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('status_category', sa.Enum('APPROVED', 'FAILED', 'PENDING', 'CANCELLED', 'REFUNDED', 'UNPROCESSED', name='paymentstatus'), nullable=False),
    sa.Column('failure_reason', sa.Enum('INSUFFICIENT_FUNDS', 'CARD_DECLINED', 'EXPIRED_CARD', 'INVALID_CARD', 'BANK_DECLINE', 'FRAUD_SUSPECTED', 'SECURITY_VIOLATION', 'BLOCKED_CARD', 'NETWORK_ERROR', 'TIMEOUT', 'PROVIDER_ERROR', 'SYSTEM_ERROR', 'INVALID_MERCHANT', 'MERCHANT_NOT_ACTIVE', 'CONFIGURATION_ERROR', 'DUPLICATE_TRANSACTION', 'AMOUNT_EXCEEDED', 'INVALID_CURRENCY', 'UNKNOWN', 'NOT_APPLICABLE', name='failurereason'), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provider_status', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('normalization_method', sa.Enum('AI_BASED', 'RULE_BASED', 'HYBRID', 'MANUAL', 'FALLBACK', name='normalizationmethod'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('normalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics', 'normalized_payment_events', ['provider', 'status_category', 'created_at'], unique=False)
    op.create_index('idx_created_at', 'normalized_payment_events', ['created_at'], unique=False)
    op.create_index('idx_merchant_country', 'normalized_payment_events', ['merchant_name', 'country'], unique=False)
    op.create_index('idx_provider_status', 'normalized_payment_events', ['provider', 'status_category'], unique=False)
    op.create_index(op.f('ix_normalized_payment_events_created_at'), 'normalized_payment_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_normalized_payment_events_id'), 'normalized_payment_events', ['id'], unique=False)
    op.create_index(op.f('ix_normalized_payment_events_merchant_name'), 'normalized_payment_events', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_normalized_payment_events_provider'), 'normalized_payment_events', ['provider'], unique=False)
    op.create_index(op.f('ix_normalized_payment_events_provider_transaction_id'), 'normalized_payment_events', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_normalized_payment_events_status_category'), 'normalized_payment_events', ['status_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_payment_events_status_category'), table_name='normalized_payment_events')
    op.drop_index(op.f('ix_normalized_payment_events_provider_transaction_id'), table_name='normalized_payment_events')
    op.drop_index(op.f('ix_normalized_payment_events_provider'), table_name='normalized_payment_events')
    op.drop_index(op.f('ix_normalized_payment_events_merchant_name'), table_name='normalized_payment_events')
    op.drop_index(op.f('ix_normalized_payment_events_id'), table_name='normalized_payment_events')
    op.drop_index(op.f('ix_normalized_payment_events_created_at'), table_name='normalized_payment_events')
    op.drop_index('idx_provider_status', table_name='normalized_payment_events')
    op.drop_index('idx_merchant_country', table_name='normalized_payment_events')
    op.drop_index('idx_created_at', table_name='normalized_payment_events')
    op.drop_index('idx_analytics', table_name='normalized_payment_events')
    op.drop_table('normalized_payment_events')
    # ### end Alembic commands ###
