"""change amount_usd to amount and currency

Revision ID: 826026dec36c
Revises: 10309e03c6ad
Create Date: 2025-12-13 18:05:29.130267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '826026dec36c'
down_revision: Union[str, Sequence[str], None] = '10309e03c6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_payment_events', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('normalized_payment_events', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False))
    op.drop_column('normalized_payment_events', 'amount_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_payment_events', sa.Column('amount_usd', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_column('normalized_payment_events', 'currency')
    op.drop_column('normalized_payment_events', 'amount')
    # ### end Alembic commands ###
