import { useState, useMemo } from 'react';
import { ReportFilters, ReportsTable } from '@/components/reports';
import { Pagination } from '@/components/Pagination';
import { FileText } from 'lucide-react';
import { useReports } from '@/hooks/useReports';
import { generateMockReports, getUniqueValues } from '@/utils/mockData';
import { scrollToTop } from '@/utils/formatters';
import { UI_MESSAGES } from '@/constants/reports';

// TODO: Replace with actual API calls
// import { fetchReports, fetchMerchants, fetchProvidersByMerchant } from '@/services/reportService';

export const ReportsPage = () => {
    // TODO: Replace mock data with API call
    // const { data: reports, loading, error } = useFetchReports();
    const [mockReports] = useState(() => generateMockReports());

    const {
        filteredReports,
        paginatedReports,
        currentPage,
        totalPages,
        filters,
        handleFilterChange,
        handleClearFilters,
        handlePageChange,
    } = useReports(mockReports);

    // TODO: Fetch from API
    // const { data: merchants } = useFetchMerchants();
    // const { data: providers } = useFetchProviders(filters.merchant);
    
    // Get unique merchants and providers for filters (mock data)
    const merchants = useMemo(
        () => getUniqueValues(mockReports, 'merchant'),
        [mockReports]
    );

    const providers = useMemo(
        () => getUniqueValues(mockReports, 'provider'),
        [mockReports]
    );

    const handlePageChangeWithScroll = (page: number) => {
        handlePageChange(page);
        scrollToTop();
    };

    return (
        <div className="container mx-auto px-4 py-8">
            {/* Header */}
            <div className="mb-6">
                <div className="flex items-center gap-3 mb-2">
                    <FileText size={32} className="text-blue-600" />
                    <h1 className="text-3xl font-bold text-gray-900">Alert Reports</h1>
                </div>
                <p className="text-gray-600">
                    Manage and review reports generated by the alert system
                </p>
            </div>

            {/* Filters */}
            <ReportFilters
                filters={filters}
                onFilterChange={handleFilterChange}
                onClearFilters={handleClearFilters}
                merchants={merchants}
                providers={providers}
            />

            {/* Results count */}
            <div className="mb-4 text-sm text-gray-600">
                {UI_MESSAGES.REPORTS.SHOWING_RESULTS(
                    paginatedReports.length,
                    filteredReports.length
                )}
            </div>

            {/* Reports Table */}
            <ReportsTable reports={paginatedReports} />

            {/* Pagination */}
            {totalPages > 1 && (
                <Pagination
                    currentPage={currentPage}
                    totalPages={totalPages}
                    onPageChange={handlePageChangeWithScroll}
                />
            )}
        </div>
    );
};
